apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset-exercise02
  labels:
    app: nginx-server-exercise2  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-server-exercise2
  template:
    metadata:
      labels:
        app: nginx-server-exercise2     
    spec:
      containers:
      - name: nginx
        image: nginx
      containers:
      - name: nginx-cont
        image: nginx:1.19.4
        resources:
          limits:
            cpu: 100m
            memory: "256Mi"
          requests:
            cpu: 100m
            memory: "256Mi"