apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-exercise04
  labels:
    app: nginx-server
spec:
  replicas: 3
  strategy: 
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx-server
  template:
    metadata:
      labels:
        app: nginx-server
        version: V3        
    spec:
      containers:
        - name: nginx-cont
          image: nginx:1.19.4
          resources:
            requests:
              memory: "156Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "100m"
