apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-exercise01
  labels:
    app: nginx-server
spec:
  containers:
    - name: nginx-cont
      image: nginx:1.19.4
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "100m"
          memory: "256Mi"