apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset-exercise03
  labels:
    app: nginx-server-exercise3  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-server-exercise3
  template:
    metadata:
      labels:
        app: nginx-server-exercise3     
    spec:
      containers:
      - name: nginx
        image: nginx
      containers:
      - name: nginx-cont
        image: nginx:1.19.4