apiVersion: v1
kind: Service
metadata:
  name: nginx-exercise3-service3
spec:
  type: NodePort
  selector:
    app: nginx-server-exercise2
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31234