apiVersion: v1
kind: Service 
metadata:
  name: nginx-exercise3-service1
spec:
  type: LoadBalancer
  selector:
    app: nginx-server-exercise2
  ports:
    - port: 8080 
      targetPort: 80
