apiVersion: v1
kind: Service
metadata:
  name: nginx-exercise3-service3
spec:
  type: NodePort
  selector:
    app: nginx-server-exercise3
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 31234
    protocol: TCP 