apiVersion: v1
kind: Service 
metadata:
  name: nginx-exercise3-service2
spec:
  type: ClusterIP
  selector:
    app: nginx-server-exercise3
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP     