apiVersion: v1
kind: Service 
metadata:
  name: nginx-serviceblue-exercise5
  labels:
    app: nginx-serviceblue-exercise5 
spec:
  type: NodePort
  selector:
    app: nginx-server
    version: v1.0
  ports:
    - port: 8080 
      targetPort: 80
      nodePort: 31567